//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Settings/Input/GameInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInput"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""f0209f7e-cacd-4ecd-a5dc-b25e49441a18"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""2fc1d1a7-3e9a-4d92-a218-a225f4e4e212"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""8818a179-e179-4431-bc57-b88d927330f6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Sidestep"",
                    ""type"": ""Button"",
                    ""id"": ""408d6279-b765-4ee9-bc39-af9b001fb232"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interaction"",
                    ""type"": ""Button"",
                    ""id"": ""4c2dc12e-7e43-4047-bfdc-07e929df331f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AttackMain"",
                    ""type"": ""Button"",
                    ""id"": ""46e515f0-7e50-438e-947e-c61fea4a38e0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold,Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AttackSub"",
                    ""type"": ""Button"",
                    ""id"": ""fe49fdcd-ff11-4d34-b4cf-5d7688a14053"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reload"",
                    ""type"": ""Button"",
                    ""id"": ""7c12cc17-e1ed-47b7-b712-b8aa597db4a8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeaponFirst"",
                    ""type"": ""Button"",
                    ""id"": ""259e1e40-6958-49a4-b06b-d18cb1647e87"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeaponSecond"",
                    ""type"": ""Button"",
                    ""id"": ""f9525c48-1941-48c4-bbf6-4bdde0db3853"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LoopSwitchWeapon"",
                    ""type"": ""Button"",
                    ""id"": ""8051dc82-d9a4-4695-a9cd-7fd080989ade"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseSkill1"",
                    ""type"": ""Button"",
                    ""id"": ""2c3fc1bb-5f6e-4d0f-9f6b-31ad50603784"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseSkill2"",
                    ""type"": ""Button"",
                    ""id"": ""b5d43502-6f7d-4dd9-8aee-4f5faf790b5c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseSkill3"",
                    ""type"": ""Button"",
                    ""id"": ""4b69f41f-c1fa-4731-84c0-2de1feca0d01"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""624cffd1-f22d-4ebe-a161-c69cd7355850"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Gamepad Left Stick"",
                    ""id"": ""d4c4465a-f155-45cf-bba5-e29d1d30a6bf"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9c75a53d-ebdb-4894-985a-66c7d0b34bec"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""4315ba5c-6410-4993-a9f5-d97bdfdd2cdf"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""5fff5d2b-b1f0-4ed9-baa0-549667372cae"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e1b67ae7-02ec-47d1-8b48-27d210bbaaeb"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard WASD"",
                    ""id"": ""242a0101-31d7-4d8a-8e77-5d10db9ff4c9"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""09478d7d-2c5c-4fc2-a337-5525fb4738f2"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""dfedbbee-eeb7-44d9-8d70-419a9b4ffdc8"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""2cec022b-e640-45dc-8559-d39d261b8354"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""02de3bb6-340e-40d6-b7b9-50b269d458d7"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard Arrows"",
                    ""id"": ""e9253b7b-2e75-43a1-a788-ed855e30e522"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""3b24b589-1da5-4a56-bf0e-a9d1081958bc"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b3cf7237-65c3-4f0d-9b69-af0e62def3f3"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""184c72ad-aea6-48ca-89ce-05080dcbae6c"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""2cbc9a38-0354-4a1f-a6fe-87d57ac47a4c"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d79f8210-9f39-4b9f-9e77-c2ada1205f8c"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sidestep"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9b622806-6a18-401a-a4a4-6fabb519fb3c"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sidestep"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""69c015fe-f0fa-4e98-83fb-88d241472bfe"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""caadf01b-5569-4fb6-adb5-f9dc61941355"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5232c89d-35b7-4db0-b7bd-c8a3a5cfd774"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AttackMain"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""466cabfb-9785-4cf5-a84c-551925ed9bf8"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AttackMain"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f3d6f07-d888-4d55-ae71-8eb533aad6a4"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AttackSub"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""75878a56-807d-4fc2-a891-f8af650fc66e"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AttackSub"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e9cedd01-fc49-402f-a9a4-0856dc79fbe5"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1fdf5297-f48c-4cd8-8e11-5156a23219fe"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8488357-7b35-4aa0-8e3d-43e6e45def67"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeaponFirst"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f74f6702-543c-4cd9-a9d4-7ccf68b179c4"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeaponFirst"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""20c64a7b-afcb-41af-9f98-61ac71becf8c"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeaponSecond"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""830b66c4-a982-45ce-a8f8-2537e2bc93bd"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeaponSecond"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78874cf7-2696-4587-9566-f2666598d404"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseSkill1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fe397f8b-9266-414c-91d0-c825e64cad4f"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseSkill1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""df6c2ee1-1d95-4b65-8b06-7df343a06ec6"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseSkill2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a78eef6-a56d-4355-a6f0-9daa95b4c6d1"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseSkill2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""49d24143-883e-4775-aba0-13cb2b0cb4c7"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseSkill3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f1113e9f-8e8b-4690-ae78-3d15c04f2d25"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseSkill3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fc9d1853-78e5-4bd2-a6f3-aea7198df482"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f7af1653-63ab-42ca-9a10-3bf7f24812d6"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bae2bbf2-89e9-4659-aa07-75e2ab20cb20"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoopSwitchWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Gamepad Right Stick"",
                    ""id"": ""74ceae2e-94a4-42f9-98f4-f87d130c8020"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d9620b42-58e4-43cd-a5ec-3eb074e0c298"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""fd2d8eea-d4fc-48c3-8bd0-230e7c599663"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""235f5f98-298a-4476-bc89-cb7ea0f303f2"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b79f4aa2-7fcc-4f15-a4c1-6fd843c4359b"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""Menu"",
            ""id"": ""4470c1b2-5acb-4614-9ee3-bfd676312eae"",
            ""actions"": [
                {
                    ""name"": ""CloseMenu"",
                    ""type"": ""Button"",
                    ""id"": ""c14e15b2-bb9c-4d9b-9e42-0ecde5c95a33"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""fb814b59-d73d-4415-aef0-5ea4947a1233"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Debug"",
            ""id"": ""cbe538b2-48cd-48c2-8d84-274bc70dee24"",
            ""actions"": [
                {
                    ""name"": ""Debug1"",
                    ""type"": ""Button"",
                    ""id"": ""5affee8b-a321-4c9a-99e5-1a17665bb8f5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Debug2"",
                    ""type"": ""Button"",
                    ""id"": ""78cb11ce-372a-4c67-ae8c-f3270fde949f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Debug3"",
                    ""type"": ""Button"",
                    ""id"": ""3ebfa6d4-2cc4-4bd7-a3e5-da3d019f632d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Debug4"",
                    ""type"": ""Button"",
                    ""id"": ""b6b7666e-c5da-4d63-afc1-fcc127a9f3d5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Debug5"",
                    ""type"": ""Button"",
                    ""id"": ""eb6683d9-d6d8-4209-a3e8-890a5af86307"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Debug6"",
                    ""type"": ""Button"",
                    ""id"": ""11656402-a902-4fac-95b6-197a5f8ad9e2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""317dd14c-830e-4696-9b76-8e29045cd940"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Debug1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""222db83e-34b0-4a2a-8694-46d333665105"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Debug2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""df78890a-643a-45ec-aa32-671bade61984"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Debug4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c838880-1884-45d1-9e42-e968264882b4"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Debug3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a5e83d5e-6582-44b8-a9a6-e5d36b843b79"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Debug5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1a636833-e411-4718-a627-bd7bf7e770a1"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Debug6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_Move = m_Gameplay.FindAction("Move", throwIfNotFound: true);
        m_Gameplay_Look = m_Gameplay.FindAction("Look", throwIfNotFound: true);
        m_Gameplay_Sidestep = m_Gameplay.FindAction("Sidestep", throwIfNotFound: true);
        m_Gameplay_Interaction = m_Gameplay.FindAction("Interaction", throwIfNotFound: true);
        m_Gameplay_AttackMain = m_Gameplay.FindAction("AttackMain", throwIfNotFound: true);
        m_Gameplay_AttackSub = m_Gameplay.FindAction("AttackSub", throwIfNotFound: true);
        m_Gameplay_Reload = m_Gameplay.FindAction("Reload", throwIfNotFound: true);
        m_Gameplay_WeaponFirst = m_Gameplay.FindAction("WeaponFirst", throwIfNotFound: true);
        m_Gameplay_WeaponSecond = m_Gameplay.FindAction("WeaponSecond", throwIfNotFound: true);
        m_Gameplay_LoopSwitchWeapon = m_Gameplay.FindAction("LoopSwitchWeapon", throwIfNotFound: true);
        m_Gameplay_UseSkill1 = m_Gameplay.FindAction("UseSkill1", throwIfNotFound: true);
        m_Gameplay_UseSkill2 = m_Gameplay.FindAction("UseSkill2", throwIfNotFound: true);
        m_Gameplay_UseSkill3 = m_Gameplay.FindAction("UseSkill3", throwIfNotFound: true);
        m_Gameplay_Pause = m_Gameplay.FindAction("Pause", throwIfNotFound: true);
        // Menu
        m_Menu = asset.FindActionMap("Menu", throwIfNotFound: true);
        m_Menu_CloseMenu = m_Menu.FindAction("CloseMenu", throwIfNotFound: true);
        // Debug
        m_Debug = asset.FindActionMap("Debug", throwIfNotFound: true);
        m_Debug_Debug1 = m_Debug.FindAction("Debug1", throwIfNotFound: true);
        m_Debug_Debug2 = m_Debug.FindAction("Debug2", throwIfNotFound: true);
        m_Debug_Debug3 = m_Debug.FindAction("Debug3", throwIfNotFound: true);
        m_Debug_Debug4 = m_Debug.FindAction("Debug4", throwIfNotFound: true);
        m_Debug_Debug5 = m_Debug.FindAction("Debug5", throwIfNotFound: true);
        m_Debug_Debug6 = m_Debug.FindAction("Debug6", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private IGameplayActions m_GameplayActionsCallbackInterface;
    private readonly InputAction m_Gameplay_Move;
    private readonly InputAction m_Gameplay_Look;
    private readonly InputAction m_Gameplay_Sidestep;
    private readonly InputAction m_Gameplay_Interaction;
    private readonly InputAction m_Gameplay_AttackMain;
    private readonly InputAction m_Gameplay_AttackSub;
    private readonly InputAction m_Gameplay_Reload;
    private readonly InputAction m_Gameplay_WeaponFirst;
    private readonly InputAction m_Gameplay_WeaponSecond;
    private readonly InputAction m_Gameplay_LoopSwitchWeapon;
    private readonly InputAction m_Gameplay_UseSkill1;
    private readonly InputAction m_Gameplay_UseSkill2;
    private readonly InputAction m_Gameplay_UseSkill3;
    private readonly InputAction m_Gameplay_Pause;
    public struct GameplayActions
    {
        private @GameInput m_Wrapper;
        public GameplayActions(@GameInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Gameplay_Move;
        public InputAction @Look => m_Wrapper.m_Gameplay_Look;
        public InputAction @Sidestep => m_Wrapper.m_Gameplay_Sidestep;
        public InputAction @Interaction => m_Wrapper.m_Gameplay_Interaction;
        public InputAction @AttackMain => m_Wrapper.m_Gameplay_AttackMain;
        public InputAction @AttackSub => m_Wrapper.m_Gameplay_AttackSub;
        public InputAction @Reload => m_Wrapper.m_Gameplay_Reload;
        public InputAction @WeaponFirst => m_Wrapper.m_Gameplay_WeaponFirst;
        public InputAction @WeaponSecond => m_Wrapper.m_Gameplay_WeaponSecond;
        public InputAction @LoopSwitchWeapon => m_Wrapper.m_Gameplay_LoopSwitchWeapon;
        public InputAction @UseSkill1 => m_Wrapper.m_Gameplay_UseSkill1;
        public InputAction @UseSkill2 => m_Wrapper.m_Gameplay_UseSkill2;
        public InputAction @UseSkill3 => m_Wrapper.m_Gameplay_UseSkill3;
        public InputAction @Pause => m_Wrapper.m_Gameplay_Pause;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void SetCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMove;
                @Look.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnLook;
                @Sidestep.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSidestep;
                @Sidestep.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSidestep;
                @Sidestep.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSidestep;
                @Interaction.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInteraction;
                @Interaction.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInteraction;
                @Interaction.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInteraction;
                @AttackMain.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAttackMain;
                @AttackMain.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAttackMain;
                @AttackMain.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAttackMain;
                @AttackSub.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAttackSub;
                @AttackSub.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAttackSub;
                @AttackSub.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAttackSub;
                @Reload.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnReload;
                @Reload.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnReload;
                @Reload.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnReload;
                @WeaponFirst.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnWeaponFirst;
                @WeaponFirst.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnWeaponFirst;
                @WeaponFirst.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnWeaponFirst;
                @WeaponSecond.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnWeaponSecond;
                @WeaponSecond.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnWeaponSecond;
                @WeaponSecond.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnWeaponSecond;
                @LoopSwitchWeapon.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnLoopSwitchWeapon;
                @LoopSwitchWeapon.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnLoopSwitchWeapon;
                @LoopSwitchWeapon.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnLoopSwitchWeapon;
                @UseSkill1.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnUseSkill1;
                @UseSkill1.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnUseSkill1;
                @UseSkill1.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnUseSkill1;
                @UseSkill2.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnUseSkill2;
                @UseSkill2.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnUseSkill2;
                @UseSkill2.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnUseSkill2;
                @UseSkill3.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnUseSkill3;
                @UseSkill3.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnUseSkill3;
                @UseSkill3.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnUseSkill3;
                @Pause.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPause;
            }
            m_Wrapper.m_GameplayActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @Sidestep.started += instance.OnSidestep;
                @Sidestep.performed += instance.OnSidestep;
                @Sidestep.canceled += instance.OnSidestep;
                @Interaction.started += instance.OnInteraction;
                @Interaction.performed += instance.OnInteraction;
                @Interaction.canceled += instance.OnInteraction;
                @AttackMain.started += instance.OnAttackMain;
                @AttackMain.performed += instance.OnAttackMain;
                @AttackMain.canceled += instance.OnAttackMain;
                @AttackSub.started += instance.OnAttackSub;
                @AttackSub.performed += instance.OnAttackSub;
                @AttackSub.canceled += instance.OnAttackSub;
                @Reload.started += instance.OnReload;
                @Reload.performed += instance.OnReload;
                @Reload.canceled += instance.OnReload;
                @WeaponFirst.started += instance.OnWeaponFirst;
                @WeaponFirst.performed += instance.OnWeaponFirst;
                @WeaponFirst.canceled += instance.OnWeaponFirst;
                @WeaponSecond.started += instance.OnWeaponSecond;
                @WeaponSecond.performed += instance.OnWeaponSecond;
                @WeaponSecond.canceled += instance.OnWeaponSecond;
                @LoopSwitchWeapon.started += instance.OnLoopSwitchWeapon;
                @LoopSwitchWeapon.performed += instance.OnLoopSwitchWeapon;
                @LoopSwitchWeapon.canceled += instance.OnLoopSwitchWeapon;
                @UseSkill1.started += instance.OnUseSkill1;
                @UseSkill1.performed += instance.OnUseSkill1;
                @UseSkill1.canceled += instance.OnUseSkill1;
                @UseSkill2.started += instance.OnUseSkill2;
                @UseSkill2.performed += instance.OnUseSkill2;
                @UseSkill2.canceled += instance.OnUseSkill2;
                @UseSkill3.started += instance.OnUseSkill3;
                @UseSkill3.performed += instance.OnUseSkill3;
                @UseSkill3.canceled += instance.OnUseSkill3;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
            }
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);

    // Menu
    private readonly InputActionMap m_Menu;
    private IMenuActions m_MenuActionsCallbackInterface;
    private readonly InputAction m_Menu_CloseMenu;
    public struct MenuActions
    {
        private @GameInput m_Wrapper;
        public MenuActions(@GameInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @CloseMenu => m_Wrapper.m_Menu_CloseMenu;
        public InputActionMap Get() { return m_Wrapper.m_Menu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MenuActions set) { return set.Get(); }
        public void SetCallbacks(IMenuActions instance)
        {
            if (m_Wrapper.m_MenuActionsCallbackInterface != null)
            {
                @CloseMenu.started -= m_Wrapper.m_MenuActionsCallbackInterface.OnCloseMenu;
                @CloseMenu.performed -= m_Wrapper.m_MenuActionsCallbackInterface.OnCloseMenu;
                @CloseMenu.canceled -= m_Wrapper.m_MenuActionsCallbackInterface.OnCloseMenu;
            }
            m_Wrapper.m_MenuActionsCallbackInterface = instance;
            if (instance != null)
            {
                @CloseMenu.started += instance.OnCloseMenu;
                @CloseMenu.performed += instance.OnCloseMenu;
                @CloseMenu.canceled += instance.OnCloseMenu;
            }
        }
    }
    public MenuActions @Menu => new MenuActions(this);

    // Debug
    private readonly InputActionMap m_Debug;
    private IDebugActions m_DebugActionsCallbackInterface;
    private readonly InputAction m_Debug_Debug1;
    private readonly InputAction m_Debug_Debug2;
    private readonly InputAction m_Debug_Debug3;
    private readonly InputAction m_Debug_Debug4;
    private readonly InputAction m_Debug_Debug5;
    private readonly InputAction m_Debug_Debug6;
    public struct DebugActions
    {
        private @GameInput m_Wrapper;
        public DebugActions(@GameInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Debug1 => m_Wrapper.m_Debug_Debug1;
        public InputAction @Debug2 => m_Wrapper.m_Debug_Debug2;
        public InputAction @Debug3 => m_Wrapper.m_Debug_Debug3;
        public InputAction @Debug4 => m_Wrapper.m_Debug_Debug4;
        public InputAction @Debug5 => m_Wrapper.m_Debug_Debug5;
        public InputAction @Debug6 => m_Wrapper.m_Debug_Debug6;
        public InputActionMap Get() { return m_Wrapper.m_Debug; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DebugActions set) { return set.Get(); }
        public void SetCallbacks(IDebugActions instance)
        {
            if (m_Wrapper.m_DebugActionsCallbackInterface != null)
            {
                @Debug1.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebug1;
                @Debug1.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebug1;
                @Debug1.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebug1;
                @Debug2.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebug2;
                @Debug2.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebug2;
                @Debug2.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebug2;
                @Debug3.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebug3;
                @Debug3.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebug3;
                @Debug3.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebug3;
                @Debug4.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebug4;
                @Debug4.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebug4;
                @Debug4.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebug4;
                @Debug5.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebug5;
                @Debug5.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebug5;
                @Debug5.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebug5;
                @Debug6.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebug6;
                @Debug6.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebug6;
                @Debug6.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebug6;
            }
            m_Wrapper.m_DebugActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Debug1.started += instance.OnDebug1;
                @Debug1.performed += instance.OnDebug1;
                @Debug1.canceled += instance.OnDebug1;
                @Debug2.started += instance.OnDebug2;
                @Debug2.performed += instance.OnDebug2;
                @Debug2.canceled += instance.OnDebug2;
                @Debug3.started += instance.OnDebug3;
                @Debug3.performed += instance.OnDebug3;
                @Debug3.canceled += instance.OnDebug3;
                @Debug4.started += instance.OnDebug4;
                @Debug4.performed += instance.OnDebug4;
                @Debug4.canceled += instance.OnDebug4;
                @Debug5.started += instance.OnDebug5;
                @Debug5.performed += instance.OnDebug5;
                @Debug5.canceled += instance.OnDebug5;
                @Debug6.started += instance.OnDebug6;
                @Debug6.performed += instance.OnDebug6;
                @Debug6.canceled += instance.OnDebug6;
            }
        }
    }
    public DebugActions @Debug => new DebugActions(this);
    public interface IGameplayActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnSidestep(InputAction.CallbackContext context);
        void OnInteraction(InputAction.CallbackContext context);
        void OnAttackMain(InputAction.CallbackContext context);
        void OnAttackSub(InputAction.CallbackContext context);
        void OnReload(InputAction.CallbackContext context);
        void OnWeaponFirst(InputAction.CallbackContext context);
        void OnWeaponSecond(InputAction.CallbackContext context);
        void OnLoopSwitchWeapon(InputAction.CallbackContext context);
        void OnUseSkill1(InputAction.CallbackContext context);
        void OnUseSkill2(InputAction.CallbackContext context);
        void OnUseSkill3(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
    }
    public interface IMenuActions
    {
        void OnCloseMenu(InputAction.CallbackContext context);
    }
    public interface IDebugActions
    {
        void OnDebug1(InputAction.CallbackContext context);
        void OnDebug2(InputAction.CallbackContext context);
        void OnDebug3(InputAction.CallbackContext context);
        void OnDebug4(InputAction.CallbackContext context);
        void OnDebug5(InputAction.CallbackContext context);
        void OnDebug6(InputAction.CallbackContext context);
    }
}
